Repository danparizher/Pax-Academia, pull requests merged in 2023-08, with the labels that each got.

#212 Added CodeDetect Cog
  ENVIRONMENT.md
  cogs/DetectCode.py
  cogs/Tips.py
  main.py
Labels: feature

#222 fix: Use official deepl library
  ENVIRONMENT.md
  cogs/DeepL.py
  main.py
  requirements.txt
  util/deepl_update.py
Labels: enhancement, bugfix

#214 created new documentation for cogs and utils
  cogs/README.md
  util/README.md
  util/db_builder.py
Labels: documentation

#216 Redesign Code Detection System for Improved Accuracy and Performance
  ENVIRONMENT.md
  cogs/DetectCode.py
  cogs/alerts.py
  cogs/deepl.py
  cogs/detect_ai.py
  cogs/detect_code.py
  cogs/dictionary.py
  cogs/message_counter.py
  cogs/misc.py
  cogs/moderation.py
  cogs/pubchem.py
  cogs/rules.py
  cogs/staffapps_backend.py
  cogs/staffapps_frontend.py
  cogs/surveys.py
  cogs/tips.py
  cogs/wikipedia.py
  main.py
  util/Logging.py
  util/code_detection/__init__.py
  util/code_detection/base.py
  util/code_detection/java.py
  util/code_detection/python.py
  util/code_detection/test_base.py
  util/embed_builder.py
Labels: enhancement, feature

#213 feat: add `view-logs` command
  ENVIRONMENT.md
  cogs/README.md
  cogs/misc.py
  cogs/staffapps_backend.py
  requirements.txt
Labels: feature

#224 Ska.better devtools
  .gitignore
  util/dev.py
Labels: enhancement

#227 Fixes surveys.py to not log every message and moves a hardcoded channel ID to .env
  ENVIRONMENT.md
  cogs/README.md
  cogs/surveys.py
  cogs/wikipedia.py
  util/embed_builder.py
Labels: bugfix

#228 refactor(part 1): utils
  code_detection/__init__.py
  code_detection/base.py
  code_detection/java.py
  code_detection/python.py
  code_detection/test_base.py
  cogs/alerts.py
  cogs/deepl.py
  cogs/detect_ai.py
  cogs/detect_code.py
  cogs/dictionary.py
  cogs/message_counter.py
  cogs/misc.py
  cogs/moderation.py
  cogs/pubchem.py
  cogs/rules.py
  cogs/staffapps_backend.py
  cogs/staffapps_frontend.py
  cogs/surveys.py
  cogs/tips.py
  cogs/wikipedia.py
  database/ERD.mdj
  database/README.md
  database/__init__.py
  database/migrate.py
  database/schema.py
  main.py
  message_formatting/embeds.py
  message_formatting/views/feedback.py
  util/README.md
  util/limiter.py
  util/logger.py
Labels: refactor

#235 General Refactor
  code_detection/__init__.py
  code_detection/test_base.py
  cogs/alerts.py
  cogs/deepl.py
  cogs/detect_ai.py
  cogs/detect_code.py
  cogs/dictionary.py
  cogs/misc.py
  cogs/moderation.py
  cogs/pubchem.py
  cogs/rules.py
  cogs/staffapps_frontend.py
  cogs/surveys.py
  cogs/tips.py
  cogs/wikipedia.py
  database/__init__.py
  message_formatting/embeds.py
  util/logger.py
Labels: refactor

#237 fix: code_detection Python `try`/`for` regex & improve testing
  code_detection/python.py
  code_detection/test_base.py
  code_detection/tests/__init__.py
  code_detection/tests/base.py
  code_detection/tests/helpers.py
  code_detection/tests/python.py
  run_tests.py
Labels: enhancement

#229 refactor(part 2): resolve typing errors throughout entire codebase
  code_detection/tests/__init__.py
  cogs/alerts.py
  cogs/message_counter.py
  cogs/pubchem.py
  cogs/rules.py
  cogs/staffapps_backend.py
  cogs/staffapps_frontend.py
  cogs/surveys.py
  cogs/tips.py
  cogs/wikipedia.py
  message_formatting/embeds.py
  message_formatting/views/feedback.py
  util/limiter.py
  util/logger.py
Labels: refactor
