Repository danparizher/Pax-Academia, pull requests merged in 2023-10, with the labels that each got.

#233 Make Gabe a Code Owner
  .github/CODEOWNERS
Labels: documentation

#263 Fix Multiple Alerts
  code_detection/base.py
  code_detection/java.py
  code_detection/python.py
  code_detection/tests/base.py
  cogs/alerts.py
  cogs/deepl.py
  cogs/detect_ai.py
  cogs/detect_code.py
  cogs/dictionary.py
  cogs/message_counter.py
  cogs/misc.py
  cogs/moderation.py
  requirements.txt
Labels: bugfix

#264 feat: Improve python code detection + improve UX
  code_detection/__init__.py
  code_detection/formatting-example.gif
  code_detection/python.py
  code_detection/tests/python.py
  cogs/detect_code.py
  cogs/tips.py
Labels: enhancement

#266 Bugfix: fix `RecursionError` in code detection
  code_detection/python.py
Labels: bugfix

#248 feat: Add `code_detection` for Python tracebacks
  code_detection/__init__.py
  code_detection/python_traceback.py
  code_detection/tests/__init__.py
  code_detection/tests/helpers.py
  code_detection/tests/python_traceback.py
Labels: enhancement

#267 fix: auto-delete survey messages
  cogs/surveys.py
Labels: bugfix

#268 Enhancement: Add commit ID to /ping
  cogs/misc.py
  requirements.txt
Labels: enhancement

#270 bugfix: missing return statement in `tips`
  cogs/tips.py
Labels: bugfix
