Repository danparizher/Pax-Academia, pull requests merged in 2023-11, with the labels that each got.

#272 fix: Edge case where message has no content throws error
  code_detection/base.py
Labels: bugfix

#271 Refactor, Formatting, Requirements Automation
  .github/workflows/dependencies.yml
  code_detection/base.py
  code_detection/python.py
  code_detection/python_traceback.py
  cogs/staffapps_backend.py
  cogs/staffapps_frontend.py
  database/schema.py
  message_formatting/views/feedback.py
  requirements.txt
Labels: refactor

#274 Create PRs instead of trying to commit directly
  .github/workflows/dependencies.yml
Labels: bugfix

#275 Refactor: Update server rules
  cogs/rules.py
Labels: enhancement

#276 Bugfix: Add base branch to pull request
  .github/workflows/dependencies.yml
Labels: bugfix

#278 Bugfix: /ping correctly shows whether the bot is up to date or not
  cogs/misc.py
Labels: bugfix

#279 bugfix: pull from source
  .github/workflows/dependencies.yml
Labels: bugfix
