Repository danparizher/Pax-Academia, pull requests merged in 2023-09, with the labels that each got.

#247 feat: Add ability to make a command server-only
  ENVIRONMENT.md
  cogs/alerts.py
  cogs/misc.py
  util/limiter.py
Labels: enhancement, Safety, bugfix

#250 hotfix: Datetime object not subscribtable
  cogs/staffapps_backend.py
Labels: Hotfix

#241 Create black.yml
  .github/workflows/black.yml
Labels: feature

#232 [Proposal] Docs: A new way to contribute code to Pax.
  CONTRIBUTING.md
  README.md
Labels: documentation, Feedback wanted
